#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
IOS_DIR="${APP_DIR}/ios"
LOG_DIR="${APP_DIR}/build_logs"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${LOG_DIR}/ios_build_${TIMESTAMP}.log"

mkdir -p "${LOG_DIR}"

log() {
  printf '[ios-build] %s\n' "$*" | tee -a "${LOG_FILE}"
}

fail() {
  log "ERROR: $*"
  exit 1
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "Required command not found: $1"
  fi
}

decode_base64_to_file() {
  local payload="$1"
  local destination="$2"

  mkdir -p "$(dirname "${destination}")"

  if base64 --help 2>/dev/null | grep -q -- '--decode'; then
    printf '%s' "${payload}" | base64 --decode > "${destination}"
  else
    printf '%s' "${payload}" | base64 -D > "${destination}"
  fi
}

cleanup() {
  if [[ -n "${TEMP_GOOGLE_SERVICE_INFO_PATH:-}" && -f "${TEMP_GOOGLE_SERVICE_INFO_PATH}" ]]; then
    rm -f "${TEMP_GOOGLE_SERVICE_INFO_PATH}"
    log "Removed injected GoogleService-Info.plist after build."
  fi
}

trap cleanup EXIT

require_command flutter
require_command dart

HOST_OS="$(uname -s 2>/dev/null || echo unknown)"

{
  echo '=== Toolchain Versions ==='
  flutter --version
  dart --version
  if [[ "${HOST_OS}" == "Darwin" ]]; then
    require_command xcodebuild
    require_command pod
    xcodebuild -version
    pod --version
  else
    echo "xcodebuild: unavailable on ${HOST_OS}"
    echo "pod: unavailable on ${HOST_OS}"
  fi
  echo
} | tee -a "${LOG_FILE}"

[[ -f "${APP_DIR}/pubspec.yaml" ]] || fail "Missing ${APP_DIR}/pubspec.yaml"
[[ -d "${IOS_DIR}" ]] || fail "Missing ${IOS_DIR}"
[[ -f "${IOS_DIR}/Podfile" ]] || fail "Missing ${IOS_DIR}/Podfile"
[[ -d "${IOS_DIR}/Runner.xcodeproj" ]] || fail "Missing ${IOS_DIR}/Runner.xcodeproj"

if [[ -n "${IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64:-}" ]]; then
  TEMP_GOOGLE_SERVICE_INFO_PATH="${IOS_DIR}/Runner/GoogleService-Info.plist"
  decode_base64_to_file "${IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64}" "${TEMP_GOOGLE_SERVICE_INFO_PATH}"
  export GOOGLE_SERVICE_INFO_PRESENT=true
  log "Injected GoogleService-Info.plist from CI secret."
fi

BUILD_NAME="${IOS_BUILD_NAME:-${APP_BUILD_NAME:-1.0.0}}"
BUILD_NUMBER="${IOS_BUILD_NUMBER:-${APP_BUILD_NUMBER:-${CM_BUILD_NUMBER:-1}}}"
APP_ENV_VALUE="${APP_ENV:-production}"
API_BASE_URL_VALUE="${API_BASE_URL:-}"
USE_FIREBASE_VALUE="${USE_FIREBASE:-false}"
GOOGLE_SERVICE_INFO_PRESENT_VALUE="${GOOGLE_SERVICE_INFO_PRESENT:-false}"
FORCE_CLEAN="${FORCE_FLUTTER_CLEAN:-0}"
IOS_NO_CODESIGN_VALUE="${IOS_NO_CODESIGN:-0}"

if [[ -f "${IOS_DIR}/Runner/GoogleService-Info.plist" ]]; then
  GOOGLE_SERVICE_INFO_PRESENT_VALUE="true"
fi

if [[ "${FORCE_CLEAN}" == "1" ]]; then
  log "Running flutter clean because FORCE_FLUTTER_CLEAN=1"
  (
    cd "${APP_DIR}"
    flutter clean
  ) 2>&1 | tee -a "${LOG_FILE}" || fail "flutter clean failed"
else
  log "Skipping flutter clean (default for faster and more deterministic CI)."
fi

log "Running flutter pub get"
(
  cd "${APP_DIR}"
  flutter pub get
) 2>&1 | tee -a "${LOG_FILE}" || fail "flutter pub get failed"

if [[ "${HOST_OS}" != "Darwin" ]]; then
  fail "iOS builds require macOS (Darwin). Current host: ${HOST_OS}"
fi

log "Installing CocoaPods dependencies"
POD_INSTALL_FLAGS=(install)
if [[ -f "${IOS_DIR}/Podfile.lock" ]]; then
  POD_INSTALL_FLAGS+=(--deployment)
  log "Podfile.lock found; using pod install --deployment for deterministic CI."
else
  log "Podfile.lock is missing; using plain pod install. Commit Podfile.lock after a successful local install for stricter CI reproducibility."
fi

(
  cd "${IOS_DIR}"
  pod "${POD_INSTALL_FLAGS[@]}"
) 2>&1 | tee -a "${LOG_FILE}" || fail "pod install failed"

[[ -d "${IOS_DIR}/Runner.xcworkspace" ]] || fail "Runner.xcworkspace was not generated by pod install"

BUILD_CMD=(flutter build ipa --release "--build-name=${BUILD_NAME}" "--build-number=${BUILD_NUMBER}")

if [[ "${IOS_NO_CODESIGN_VALUE}" == "1" ]]; then
  BUILD_CMD=(flutter build ios --release --no-codesign "--build-name=${BUILD_NAME}" "--build-number=${BUILD_NUMBER}")
  log "Using flutter build ios --no-codesign because IOS_NO_CODESIGN=1"
fi

if [[ -n "${API_BASE_URL_VALUE}" ]]; then
  BUILD_CMD+=("--dart-define=API_BASE_URL=${API_BASE_URL_VALUE}")
fi

BUILD_CMD+=("--dart-define=APP_ENV=${APP_ENV_VALUE}")

if [[ "${USE_FIREBASE_VALUE}" == "true" ]]; then
  BUILD_CMD+=("--dart-define=USE_FIREBASE=true")
  if [[ "${GOOGLE_SERVICE_INFO_PRESENT_VALUE}" == "true" ]]; then
    BUILD_CMD+=("--dart-define=GOOGLE_SERVICE_INFO_PRESENT=true")
  fi
fi

if [[ -n "${IOS_EXPORT_OPTIONS_PLIST:-}" ]]; then
  BUILD_CMD+=("--export-options-plist=${IOS_EXPORT_OPTIONS_PLIST}")
fi

log "Running: ${BUILD_CMD[*]}"
(
  cd "${APP_DIR}"
  "${BUILD_CMD[@]}"
) 2>&1 | tee -a "${LOG_FILE}" || fail "Flutter iOS build failed"

if [[ "${IOS_NO_CODESIGN_VALUE}" == "1" ]]; then
  APP_BUNDLE_PATH="${APP_DIR}/build/ios/iphoneos/Runner.app"
  [[ -d "${APP_BUNDLE_PATH}" ]] || fail "Expected Runner.app not found at ${APP_BUNDLE_PATH}"
  log "No-code-sign build completed: ${APP_BUNDLE_PATH}"
else
  IPA_PATH="$(find "${APP_DIR}/build/ios/ipa" -maxdepth 1 -name '*.ipa' | head -n 1 || true)"
  [[ -n "${IPA_PATH}" ]] || fail "No IPA found under ${APP_DIR}/build/ios/ipa"
  [[ -f "${IPA_PATH}" ]] || fail "IPA path does not exist: ${IPA_PATH}"
  log "IPA generated successfully: ${IPA_PATH}"
fi

INFO_PLIST_PATH="${IOS_DIR}/Runner/Info.plist"
if [[ -f "${INFO_PLIST_PATH}" ]] && command -v /usr/libexec/PlistBuddy >/dev/null 2>&1; then
  BUNDLE_ID="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "${INFO_PLIST_PATH}" 2>/dev/null || true)"
  VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "${INFO_PLIST_PATH}" 2>/dev/null || true)"
  BUILD="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "${INFO_PLIST_PATH}" 2>/dev/null || true)"
  log "Info.plist bundle id: ${BUNDLE_ID:-unknown}"
  log "Info.plist version: ${VERSION:-unknown} (${BUILD:-unknown})"
else
  log "Info.plist validation skipped (Runner/Info.plist or PlistBuddy not available in this workspace)."
fi

log "iOS build completed successfully. Full log: ${LOG_FILE}"
